spring:
  application:
    name: recipe-demo
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.application.name}
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: embedded
      data-locations: classpath:db/data.sql

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: debug

app:
  secret-key: your_secret_key
  expiration-time: 86400000